apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
        - name: golang
          image: docker.io/danisbagus/app-go
          envFrom:
            - configMapRef:
                name: golang-configmap
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: golang-volume
              mountPath: /go/.env
              subPath: .env
      imagePullSecrets:
        - name: docker-hub
      volumes:
        - name: golang-volume
          configMap:
            name: golang-configmap
